version: '3.9'
services: 
  backend: 
    build: .
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
    depends_on: 
      - db
  
  db:
    image: mysql:8.2.0
    restart: always
    environment: 
       MYSQL_DATABASE: weather
       MYSQL_ROOT_PASSWORD: root
       BASE_URL: ''
    volumes: 
      - .dbdata:/var/lib/mysql
      - ./seed:/docker-entrypoint-initdb.d
    ports: 
      - 3306:3306
